apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: deploy-api
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: webhook
      eventSourceName: github-api
      eventName: main
      filters:
        data:
          - path: body.ref
            type: string
            value:
              - "refs/heads/main"
  triggers:
    - template:
        name: api-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-api-
                namespace: argo
              spec:
                entrypoint: build-deploy-api
                arguments:
                  parameters:
                  - name: revision
                volumes:
                - name: kaniko-secret
                  secret:
                    secretName: regcred
                    items:
                      - key: .dockerconfigjson
                        path: config.json
                volumeClaimTemplates:
                - metadata:
                    name: workdir
                  spec:
                    accessModes: [ "ReadWriteOnce" ]
                    resources:
                      requests:
                        storage: 1Gi
                templates:
                - name: build-deploy-api
                  steps:
                  - - name: clone-repo
                      template: clone-repo
                  - - name: build-docker
                      template: build-docker
                - name: clone-repo
                  container:
                    image: alpine/git:latest
                    command: [sh, -c]
                    args: ["cd /mnt/vol; git clone https://github.com/ProgWeb-IDP/pweb.api.git"]
                    volumeMounts:
                    - name: workdir
                      mountPath: /mnt/vol
                - name: build-docker
                  container:
                    image: gcr.io/kaniko-project/executor:latest
                    args:
                    - "--dockerfile=/mnt/vol/pweb.api/src/Dockerfile"
                    - "--context=/mnt/vol/pweb.api/src"
                    - "--destination=lazandrei19/pweb-api:{{workflow.parameters.revision}}"
                    volumeMounts:
                    - name: workdir
                      mountPath: /mnt/vol
                    - name: kaniko-secret
                      mountPath: /kaniko/.docker/
          parameters:
            - src:
                dependencyName: webhook
                dataKey: body.after
              dest: spec.arguments.parameters.0.value