apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: default
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "UsersAppCon": "Server=mssql; User Id=MyUser; Database=dbo; Password=pass@123"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*"
    }
