apiVersion: v1
kind: Pod
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  containers:
    - name: mssql
      image: mcr.microsoft.com/mssql/server:2019-latest
      env:
        - name: ACCEPT_EULA
          value: Y
        - name: SA_PASSWORD
          value: N!uX7g8!tztCQ8!L
      ports:
        - containerPort: 1433
      resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: mssql
spec:
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433
---