---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pweb-ui
  name: pweb-ui
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: pweb-ui
  strategy: {}
  template:
    metadata:
      labels:
        app: pweb-ui
    spec:
      containers:
      - image: lazandrei19/pweb-ui:1.0
        name: pweb-ui
        resources: {}
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API
          value: https://api.devenv.click/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pweb-ui
  name: pweb-ui
  namespace: default
spec:
  ports:
  - name: web
    port: 80
    targetPort: http
  selector:
    app: pweb-ui
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  name: ui-ingress
  namespace: default
spec:
  rules:
  - host: devenv.click
    http:
      paths:
      - backend:
          service:
            name: pweb-ui
            port:
              name: web
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - devenv.click
    secretName: ui-ingress-tls